[workspace]
members = [
  # AnyTLS client & server implementations using REALITY protocol
  "anyreality",
  # Bogo test shim
  "bogo",
  # CI benchmarks
  "ci-bench",
  # Network-based tests
  "connect-tests",
  # tests and example code
  "examples",
  # Tests that require OpenSSL
  "openssl-tests",
  # the main library and tests
  "rustls",
  # AWS-LC based crypto provider
  "rustls-aws-lc-rs",
  # the ring crypto provider
  "rustls-ring",
  # common code for testing the core crate
  "rustls-test",
  # benchmarking tool
  "rustls-bench",
  # experimental post-quantum algorithm support
  "rustls-post-quantum",
  # rustls cryptography provider integration tests
  "rustls-provider-test",
  # rustls cryptography provider for fuzzing
  "rustls-fuzzing-provider",
  # utility code
  "rustls-util",
]

## Deliberately not included in `members`:
exclude = [
  # `cargo fuzz` integration (requires nightly)
  "fuzz",
]

default-members = [
  # ---
  "examples",
  "rustls",
  "rustls-aws-lc-rs",
  "rustls-ring",
  "rustls-test",
  "anyreality",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.104"
asn1 = "0.24.1"
async-trait = "0.1.92"
aws-lc-rs = { version = "1.18.1", default-features = false }
base64 = "0.23.1"
bencher = "0.1.5"
brotli = { version = "9.0.0", default-features = false, features = ["std"] }
brotli-decompressor = "6.0.0"
byteorder = "1.5.0"
clap = { version = "4.6.6", features = ["derive", "env"] }
crabgrind = "0.3.1"
criterion = "0.8.2"
env_logger = "0.11.11"
graviola = "0.4.1"
hashbrown = { version = "0.17.1", default-features = false, features = ["default-hasher", "inline-more"] }
hex = "0.4.3"
hickory-resolver = { version = "0.26.2", features = ["https-aws-lc-rs", "webpki-roots"] }
hpke-rs = "0.7.0"
hpke-rs-crypto = "0.7.0"
hpke-rs-rust-crypto = "0.7.0"
itertools = "0.15.0"
log = { version = "0.4.34" }
macro_rules_attribute = "0.2.3"
mio = { version = "1.2.3", features = ["net", "os-poll"] }
num-bigint = "0.5.1"
once_cell = { version = "1.21.4", default-features = false, features = ["alloc", "race"] }
openssl = "0.10.81"
pki-types = { package = "rustls-pki-types", version = "1.15.1", features = ["alloc"] }
rayon = "1.12.0"
rcgen = { version = "0.14.10", features = ["pem", "aws_lc_rs"], default-features = false }
regex = "1.13.1"
ring = "0.17.14"
rustc-hash = "2.1.3"
rustls-fuzzing-provider = { path = "rustls-fuzzing-provider/" }
rustls-graviola = { version = "0.4.0" }
rustls-test = { path = "rustls-test/", default-features = false }
rustls-util = { path = "rustls-util/" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
socks5-impl = "0.9.6"
subtle = { version = "2.6.1", default-features = false }
time = { version = "0.3.55", default-features = false }
tikv-jemallocator = "0.7.0"
tokio = { version = "1.53.1", features = ["io-util", "macros", "net", "rt"] }
tokio-rustls = "0.26.5"
toml = "1.1.5"
webpki = { package = "rustls-webpki", version = "=0.104.0-alpha.6", features = [
  "alloc",
], default-features = false }
webpki-roots = "1.0.9"
x509-parser = "0.18.1"
zeroize = "1.9.0"
zlib-rs = "0.6.7"

[profile.bench]
codegen-units = 1
lto = true

[workspace.lints.clippy]
alloc_instead_of_core = "warn"
cloned_instead_of_copied = "warn"
manual_let_else = "warn"
needless_collect = "warn"
needless_pass_by_ref_mut = "warn"
or_fun_call = "warn"
redundant_clone = "warn"
std_instead_of_core = "warn"
upper_case_acronyms = "warn"
use_self = "warn"

# Relax these clippy lints:
# - too_many_arguments: some things just need a lot of state, wrapping it
#   doesn't necessarily make it easier to follow what's going on
too_many_arguments = "allow"

# - new_without_default: for internal constructors, the indirection is not
#   helpful
new_without_default = "allow"

[workspace.lints.rust]
elided_lifetimes_in_paths = "warn"
trivial_numeric_casts = "warn"
unexpected_cfgs = { level = "warn", check-cfg = [
  "cfg(bench)",
  "cfg(coverage_nightly)",
  "cfg(rustls_docsrs)",
] }
unnameable_types = "warn"
unreachable_pub = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"

# ensure all our tests are against the local copy, never
# against the latest _published_ copy.
[patch.crates-io]
rustls = { path = "rustls" }
