[reality]
shortId = "aabbcc"
publicKey = "h72QTtr2UAYmGeblfKYIUsN3q4kOJQZPxq556g6eIhg"
version = "010203"
serverName = "test"

[anytls]
password = "reality-smoke-password"
idleCheckSecs = 30
idleTimeoutSecs = 30
minIdleSessions = 0

[client]
listen = "127.0.0.1:1081"
serverAddr = "127.0.0.1:9445"
caFile = "./bogo/keys/cert.pem"
insecure = true
