[package]
name = "anyreality"
version = "0.4.2"
edition = "2021"
publish = false

[[bin]]
name = "anyreality-client"
path = "bin/client.rs"

[[bin]]
name = "anyreality-server"
path = "bin/server.rs"

[dependencies]
anyhow = { workspace = true }
anytls = { version = "0.3.15", default-features = false, features = [
    "core",
    "uot",
    "runtime",
    "client",
    "server",
] }
clap = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
rustls = { path = "../rustls", features = ["log"] }
rustls-aws-lc-rs = { path = "../rustls-aws-lc-rs" }
rustls-util = { path = "../rustls-util" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
aes-gcm = "0.11.1"
hkdf = "0.13.0"
base64 = { workspace = true }
aws-lc-rs = { workspace = true }
socks5-impl = { workspace = true, features = ["server"] }
tokio = { workspace = true, features = [
    "io-std",
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }
toml = { workspace = true }
uuid = { version = "1.26.0", features = ["serde"] }
webpki-roots = { workspace = true }

[lints]
workspace = true
