[package]
name = "anyreality"
version = "0.4.5"
edition = "2024"
publish = false

[[bin]]
name = "anyreality-client"
path = "bin/client.rs"

[[bin]]
name = "anyreality-server"
path = "bin/server.rs"

[dependencies]
aes-gcm = "0.11.1"
anyhow = { workspace = true }
anytls = { version = "0.4.5", default-features = false, features = [
    "core",
    "uot",
    "runtime",
    "client",
    "server",
    "ffi",
    "relay",
] }
aws-lc-rs = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
hkdf = "0.13.0"
log = { workspace = true }
rustls = { path = "../rustls", features = ["log"] }
rustls-aws-lc-rs = { path = "../rustls-aws-lc-rs" }
rustls-util = { path = "../rustls-util" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
socks-hub = { version = "0.2.11", default-features = false, features = ["httpproxy"] }
socks5-impl = { workspace = true, features = ["server"] }
tokio = { workspace = true, features = [
    "io-std",
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }
toml = { workspace = true }
uuid = { version = "1.27.0", features = ["serde"] }
webpki-roots = { workspace = true }

[lints]
workspace = true
